package com.bsdevs.multimoduleproject

import android.app.Application
import androidx.appfunctions.AppFunctionConfiguration
import androidx.appfunctions.AppFunctionManager
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import dagger.hilt.android.HiltAndroidApp
import kotlinx.coroutines.MainScope
import kotlinx.coroutines.launch

@HiltAndroidApp
class MultiModuleProjectApplication : Application(), AppFunctionConfiguration.Provider {
    override val appFunctionConfiguration: AppFunctionConfiguration
        get() = AppFunctionConfiguration.Builder().build()

    override fun onCreate() {
        // Initialize Firebase explicitly to ensure it's ready before other components need it
        FirebaseApp.initializeApp(this)
        // Trigger FirebaseAuth initialization early
        FirebaseAuth.getInstance()
        
        super.onCreate()
        enableAppFunctions()
    }

    private fun enableAppFunctions() {
        MainScope().launch {
            try {
                val manager = AppFunctionManager.getInstance(this@MultiModuleProjectApplication)
                // Using the Fully Qualified ID as generated by KSP
                manager?.setAppFunctionEnabled(
                    "com.bsdevs.multimoduleproject.functions.BaseMMPAppFunctionService#recordNappyChange",
                    AppFunctionManager.APP_FUNCTION_STATE_ENABLED
                )
            } catch (e: Exception) {
                // Log failure: system may not be ready yet
            }
        }
    }
}
